musicgrant:
  kafka:
    song-topic: song-topic

spring:
  kafka:
    bootstrap-servers: localhost:29092
    # producer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false
