version: "3.8"

services:
  postgresql:
    image: postgres:latest
    restart: always
    env_file: ./.env
    environment:
      POSTGRES_USER: $POSTGRESDB_USER
      POSTGRES_PASSWORD: $POSTGRESDB_PASSWORD
    ports:
      - "$POSTGRESDB_PORT:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "$ADMINER_PORT:8080"
#  mysqldb:
#    image: mysql:latest
#    restart: unless-stopped
#    env_file: ./.env
#    environment:
#      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
#      - MYSQL_DATABASE=$MYSQLDB_DATABASE
#    ports:
#      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
#    volumes:
#      - db:/var/lib/mysql
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  music-service-ms:
    depends_on:
      - postgresql
      - kafka
    build: ./music-service-ms
    restart: on-failure
    env_file: ./.env
    ports:
      - $MS_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.r2dbc.url"  : "r2dbc:pool:postgresql://postgresql:$POSTGRESDB_PORT/$POSTGRESDB_NAME?useSSL=false&useUnicode=yes&characterEncoding=UTF-8",
        "spring.r2dbc.username" : "$POSTGRESDB_USER",
        "spring.r2dbc.password" : "$POSTGRESDB_PASSWORD",
        "spring.kafka.bootstrap-servers" : "kafka:$KAFKA_PORT"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  music-grant-service-ms:
    depends_on:
      - kafka
    build: ./music-grant-service-ms
    restart: on-failure
    env_file: ./.env
    ports:
      - $MGS_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.kafka.bootstrap-servers" : "kafka:$KAFKA_PORT"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
