### Docker
PUT localhost:8086/music-grant-service-ms/v1/song
Content-Type: application/json

{
  "author": "Михаил Елизаров",
  "name": "Господин Главный Ветер"
}

### Local
PUT localhost:8080/music-grant-service-ms/v1/song
Content-Type: application/json

{
  "author": "Михаил Елизаров",
  "name": "Господин Главный Ветер"
}
