### Docker
PUT localhost:8086/music-grant-service-ms/v1/song
Content-Type: application/json

{
  "author": "Rick Astley",
  "name": "Never Gonna Give You Up"
}

### Local
PUT localhost:8080/music-grant-service-ms/v1/song
Content-Type: application/json

{
  "author": "Rick Astley",
  "name": "Never Gonna Give You Up"
}
