spring:
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3307/music-db?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org:springframework:data:r2dbc:dialect:MySqlDialect
        show_sql: true
        ddl-auto: update
