musicgrant:
  kafka:
    song-topic: song-topic

spring:
  profiles:
    default: kafka, inMemoryDb
    group:
      local:
        - inMemoryDb
      docker:
        - mysqlDb
  webflux:
    base-path: /music-service-ms
  sql:
    init:
      mode: always
