spring:
  r2dbc:
    url: r2dbc:pool:h2:mem:///music-db
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org:hibernate:dialect:H2Dialect
        show_sql: true
        ddl-auto: update
