server:
  servlet:
    context-path: music-service-ms

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG

spring:
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3307/music-db?useSSL=false
    username: root
    password: 123456
