@startuml
'https://plantuml.com/sequence-diagram

autonumber

User -> "music-service-ms": GetNextSong
"music-service-ms" --> DB : GetAllowed
"music-service-ms" <-- DB
User <-- "music-service-ms"  : response

"music-service-ms" <- "music-grant-service-ms": produces changes \nin music Songs \naccessibility via kafka
"music-service-ms" -> DB : Save changes
"music-service-ms" <-- DB
@enduml
