@startuml
'https://plantuml.com/sequence-diagram

autonumber

User -> MusicService: GetNextSong
MusicService --> DB : GetAllowed
MusicService <-- DB
User <-- MusicService  : response

MusicService <- GrantMusicService: produces changes \nin music Songs \naccessibility via kafka
MusicService -> DB : Save changes
MusicService <-- DB
@enduml
