@startuml
'https://plantuml.com/sequence-diagram

autonumber

OUTDATED -> DIAGRAM

RestPactConsumer -> "music-service-ms": GetNextSong
"music-service-ms" --> DBPactProducer : GetAllowed
"music-service-ms" <-- DBPactProducer
RestPactConsumer <-- "music-service-ms"  : response

"music-service-ms" <- MQPactConsumer: produces changes \nin music Songs \naccessibility via kafka
"music-service-ms" -> DBPactConsumer : Save changes
@enduml
