@startuml
'https://plantuml.com/sequence-diagram

autonumber

RestPactConsumer -> MusicService: GetNextSong
MusicService --> DBPactProducer : GetAllowed
MusicService <-- DBPactProducer
RestPactConsumer <-- MusicService  : response

MusicService <- MQPactConsumer: produces changes \nin music Songs \naccessibility via kafka
MusicService -> DBPactConsumer : Save changes
@enduml
